// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiCzA9pOwsXRbD-Q8oftRhR2XS94kF2Zg',
    appId: '1:285547917817:android:2ecd8db07df379de7dcd28',
    messagingSenderId: '285547917817',
    projectId: 'mynotes-nothingchang',
    storageBucket: 'mynotes-nothingchang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFMX6JxSNKiLFNbeyfBFz0kWY0Jgdx2sc',
    appId: '1:285547917817:ios:89c5a0bccfb1dda87dcd28',
    messagingSenderId: '285547917817',
    projectId: 'mynotes-nothingchang',
    storageBucket: 'mynotes-nothingchang.appspot.com',
    iosClientId:
        '285547917817-jj49dh735ak5m0gk76csr039gmmk9g1e.apps.googleusercontent.com',
    iosBundleId: 'com.nothingchang.mynotes',
  );
}
